name: Test naming
on:
  push:
    tags:
    - name+*
  workflow_dispatch:
env:
  SUBWASM_VERSION: 0.16.1
  astar_runtime_version: ''
  shiden_runtime_version: ''
  shibuya_runtime_version: ''

jobs:
  create-artifacts:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chain: ["astar", "shiden", "shibuya"]
    steps:
    - name: Create dummy file
      run: touch ${{ matrix.chain }}-test-runtime.wasm

    - name: Archive Artifacts for ${{ matrix.chain }}
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.chain }}-test-runtime
        path: ${{ matrix.chain }}-test-runtime.wasm

  upload-runtimes:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chain: ["astar", "shiden", "shibuya"]
    steps:
    - name: Download dummy runtime
      uses: actions/download-artifact@v3
      with:
        name: ${{ matrix.chain }}-test-runtime

    - name: Get runtime version
      id: get-runtime-version
      run: |
        ls -R
        chain=${{ matrix.chain }}
        runtime_version=$(echo '"${{ matrix.chain }}"-"4"' | tr -d '"')
        echo $runtime_version
        echo "runtime=$(echo $runtime_version)" >> $GITHUB_ENV
        echo "${{ matrix.chain }}=$(echo $runtime_version)" >> $GITHUB_OUTPUT
      #echo "${{ matrix.chain }}=$(echo '${{ matrix.chain }}-01')" >> $GITHUB_OUTPUT

    - name: Print version
      run: |
        echo "${{ env.runtime }}.wasm"

   - name: Upload ${{ matrix.chain }} dummy Wasm
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.chain }}-test-runtime-with-version
        path: ${{ env.runtime }}.wasm

    outputs:
      astar_runtime_version: ${{ steps.get-runtime-version.outputs.astar }}
      shiden_runtime_version: ${{ steps.get-runtime-version.outputs.shiden }}
      shibuya_runtime_version: ${{ steps.get-runtime-version.outputs.shibuya }}

  tracing-runtimes:
    needs: upload-runtimes
    runs-on: ubuntu-latest
    steps:
    - name: Get Astar runtime version
      run: echo ${{needs.upload-runtimes.outputs.astar_runtime_version}}