name: Test naming
on:
  push:
    tags:
    - name+*
  workflow_dispatch:
env:
  SUBWASM_VERSION: 0.16.1

jobs:
  init-upload:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chain: ["astar", "shiden", "shibuya"]
    steps:
    - name: Create dummy file
      run: touch ${{ matrix.chain }}-test-runtime.wasm

    - name: Archive Artifacts for ${{ matrix.chain }}
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.chain }}-test-runtime
        path: ${{ matrix.chain }}-test-runtime.wasm

  upload-runtimes:
    needs: init-upload
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chain: ["astar", "shiden", "shibuya"]
    steps:
    - name: Download dummy runtime
      uses: actions/download-artifact@v3
      with:
        name: ${{ matrix.chain }}-test-runtime

    - name: Get runtime version
      id: get-runtime-version
      run: |
        ls -R
        chain=${{ matrix.chain }}
        runtime_version=$(echo '"${{ matrix.chain }}"-"4"' | tr -d '"')
        echo $runtime_version
        echo "runtime=$(echo $runtime_version)" >> $GITHUB_ENV
        echo "${{ matrix.chain }}=$(echo $runtime_version)" >> $GITHUB_OUTPUT

    - name: Print version
      run: |
        echo "${{ env.runtime }}.wasm"

    - name: Archive Artifacts for ${{ matrix.chain }} with version
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.runtime }}-versioned-runtime
        path: ${{ matrix.chain }}-test-runtime.wasm
