name: Test naming
on:
  push:
    tags:
    - name+*
  workflow_dispatch:
env:
  SUBWASM_VERSION: 0.16.1
  astar_runtime_version: ''
  shiden_runtime_version: ''
  shibuya_runtime_version: ''

jobs:
  upload-runtimes:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chain: ["astar", "shiden", "shibuya"]
    steps:
    - name: Get runtime version
      id: get-runtime-version
      run: |
        ls -R
        chain=${{ matrix.chain }}
        echo "${{ matrix.chain }}=$(echo '${{ matrix.chain }}-01')" >> $GITHUB_OUTPUT

    - name: Print version
      run: echo $${{ matrix.chain }}

    outputs:
      astar_runtime_version: ${{ steps.get-runtime-version.outputs.astar }}
      shiden_runtime_version: ${{ steps.get-runtime-version.outputs.shiden }}
      shibuya_runtime_version: ${{ steps.get-runtime-version.outputs.shibuya }}

  tracing-runtimes:
    needs: upload-runtimes
    runs-on: ubuntu-latest
    steps:
    - name: Get Astar runtime version
      run: echo ${{needs.upload-runtimes.outputs.astar_runtime_version}}