name: Test naming
on:
  push:
    tags:
    - name+*
  workflow_dispatch:
env:
  SUBWASM_VERSION: 0.16.1
jobs:
  upload-runtimes:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chain: ["astar", "shiden", "shibuya"]
    steps:
    - name: Get runtime version
      id: get-runtime-version
      run: |
        ls -R
        chain=${{ matrix.chain }}
        echo "${{ matrix.chain }}_runtime_version=$(echo '${{ matrix.chain }}-01')" >> $GITHUB_ENV

    - name: Print version
      run: echo $${{ matrix.chain }}_runtime_version

  tracing-runtimes:
    runs-on: ubuntu-latest
    strategy:
    steps:
    - name: Get Astar runtime version
      id: get-astar-runtime-version
      run: echo $astar_runtime_version