name: Test naming
on:
  push:
    tags:
    - name+*
  workflow_dispatch:
env:
  SUBWASM_VERSION: 0.16.1
jobs:
  upload-runtimes:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chain: ["astar", "shiden", "shibuya"]
    steps:
    - name: Get runtime version
      id: get-runtime-version
      run: |
        ls -R
        chain=${{ matrix.chain }}
        runtime_version=$(echo '${{ matrix.chain }}-01')
        echo $runtime_version >> $GITHUB_ENV

    - name: Print version
      run: echo $runtime_version